_format_version: "3.0"

services:
  - name: dummy-backend
    url: http://httpbin.org
    routes:
      - name: secure-route
        paths:
          - /api/v1/secure

plugins:
  - name: jwt
    config:
      claims_to_verify:
        - exp
  - name: rate-limiting
    config:
      minute: 5
      policy: local

consumers:
  - username: auth0-auth-server

# ĐÃ SỬA LỖI: Tách jwt_secrets ra thành một khối ngang hàng, liên kết bằng trường 'consumer'
jwt_secrets:
  - consumer: auth0-auth-server
    key: "https://dev-ovmjlc4xr45esio2.us.auth0.com/"
    algorithm: RS256
    rsa_public_key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArf2+yvKJBobQIg7iFASG
      fA2XCUSX6Dn53EtDjbxguuEYIuVowsuI9LqR+HzeUrfplmR5TEG+vJfrqTHiOlBM
      dFgL1W++xVfRcmxhNqLT+BptaUAp4VsLUk0JXg7sIUI8n76zPcUt2NhdI/RA0Emy
      RJsuKcwNDK27tLkxtIJoxDDiVfv2sjRObbxa9/5ykKcN7Wn44NHIzTjGAJB009nU
      5EuV2R1v81/+1fScfB4xJtcorBwJotodXljKwkEaNGkmOKSsh2pRE4TydL0F1QM5
      96oTRLwCPkT1+n5bZ2D+MZDgr/qHkwY2ZET11uvINrBPeAKOAxEa9ei7vcaEH94l
      3wIDAQAB
      -----END PUBLIC KEY-----